### ISSUE TITLE
Deferred EPP renders incorrectly

### ISSUE THREAD

**Issue by dacron** [puppetlabs/puppetlabs-apache#2500]
## Describe the Bug
Virtual Host template does not render as expected when using Kerberos authentication.

## Expected Behavior
Given the virtual host parameters:

```
    auth_kerb: true
    krb_5keytab: /etc/httpd/conf/keytab
    krb_auth_realms:
      - [REMOVED]
      - [REMOVED]
    krb_authoritative: 'On'
    krb_local_user_mapping: 'On'
    krb_method_negotiate: 'On'
    krb_servicename: [REMOVED]
    krb_verify_kdc: 'On'
```

I would expect to see the following configuration directives in resulting configuration file.

```
KrbMethodNegotiate on
KrbMethodK5Passwd on
KrbAuthoritative on
KrbAuthRealms [REMOVED]
Krb5Keytab /etc/httpd/conf/keytab
KrbLocalUserMapping on
 KrbVerifyKDC on
KrbServiceName [REMOVED]
KrbSaveCredentials off
```

## Actual result
Resulting Virtual Host file contains:

```
#<Puppet::Pops::Evaluator::DeferredValue:0x00007fe304148018>
```

## Steps to Reproduce
See expected result section for virtual host configuration directives

## Environment
 - Puppet 8.3.1
 - Puppetserver 8.3.0
 - puppetlabs-apache 11.1.0
 - puppetlabs-stdlib 9.4.1
 - puppetlabs-concat 9.0.0

## Additional Context
puppet-agent OS RHEL7
puppetserver OS RHEL9.

Template rendering was fine on Puppet 7.27.0.
